[package]
name = "cottonbook"
version = "1.0.1"
description = "CottonBook — cotton breeder trait recorder"
authors = ["Muhammad Faisal Haqani"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[profile.release]
opt-level = "s"
lto = true
strip = true
